import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ColorSchemeScript, MantineProvider } from "@mantine/core";

// core styles are required for all packages
import '@mantine/core/styles.css';
import { cn } from "@/lib/utils";
import { theme } from "./theme";

// other css files are required only if
// you are using components from the corresponding package
// import '@mantine/dates/styles.css';
// import '@mantine/dropzone/styles.css';
// import '@mantine/code-highlight/styles.css';
// ...

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={cn(inter.className, 'h-screen')}>
      <MantineProvider theme={theme}>
        {children}
      </MantineProvider>
    </div>
  );
}
